#pragma once

#define CARD_FILE_PATH "card.txt"

#define INPUT_BUFFER_SIZE 128
#define CARD_NAME_LEN 7
#define CARD_PWD_LEN 6

#define CARD_STATUS_OFFLINE 0
#define CARD_STATUS_ONLINE 1
#define CARD_STATUS_DELETED 2

#define MONEY_STATUS_RECHARGE 0
#define MONEY_STATUS_REFUND 1
